package Zad2;
import java.sql.*;

public class Cre1 {

    static public void main(String[] args) {
        new Cre1();
    }

    Statement stmt;

    Cre1() {
        Connection con = null;
        try {
            // łączenie z bazą i utworzenie obiektu typu Statement
            con = DriverManager.getConnection("jdbc:derby:C:\\DerbyDbs\\ksidb");
            stmt = con.createStatement();
        } catch (Exception exc) {
            System.out.println(exc);
            System.exit(1);
        }

        // metoda dropTable jest naszą własną metodą napisaną dla skrócenia programu
        // usuwa ona tabelę podaną jako argument
        // Aby w każdych okolicznościach stworzyć nową tabelę AUTOR
        // musimy usunąć ew.  już istniejącą tabelę AUTOR
        try {
            dropTable("POZYCJE");
            dropTable("AUTOR");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        String crestmt = "create table AUTOR (\n" +
                "        AUTID integer not null generated by default as identity,\n" +
                "        NAME varchar(255) not null,\n" +
                "        PRIMARY KEY(AUTID)\n" +
                "        )";
        try {
            stmt.executeUpdate(crestmt);
                       // wykonanie polecenia zapisanego w crestmt

        } catch (SQLException exc) {                      // przechwycenie wyjątku:
            System.out.println("SQL except.: " + exc.getMessage());
            System.out.println("SQL state  : " + exc.getSQLState());
            System.out.println("Vendor errc: " + exc.getErrorCode());
            System.exit(1);
        } finally {
            try {
                stmt.close();
                con.close();
            } catch (SQLException exc) {
                System.out.println(exc);
                System.exit(1);
            }
        }
    }

    private void dropTable(String tname) throws SQLException {
        //Brak bloku try catch przerywa działanie programu
        try {
            stmt.executeUpdate("DROP TABLE " + tname);
        }
        catch (Exception e) {
            System.out.println("Tabela " + tname + " nie istnieje!");
        }
    }
}